// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAU0M5-sJhIbDIhQ5c3EB78L2NxxjI57o',
    appId: '1:748368164925:web:8793f0a0ed44d56a665254',
    messagingSenderId: '748368164925',
    projectId: 'marmita-a24fd',
    authDomain: 'marmita-a24fd.firebaseapp.com',
    storageBucket: 'marmita-a24fd.appspot.com',
    measurementId: 'G-XBH41Q3VPZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6srErR9Uu8B8RsOD7t5lg6iOV5asBLvk',
    appId: '1:748368164925:android:1d6699903f9a253b665254',
    messagingSenderId: '748368164925',
    projectId: 'marmita-a24fd',
    storageBucket: 'marmita-a24fd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYksgN1iaL9FANPrIjjTbr-94VoVwgp4A',
    appId: '1:748368164925:ios:b0b4cabceae51a73665254',
    messagingSenderId: '748368164925',
    projectId: 'marmita-a24fd',
    storageBucket: 'marmita-a24fd.appspot.com',
    iosClientId: '748368164925-h0htf8u9vljg80ghmek9ros4nq5ovl3i.apps.googleusercontent.com',
    iosBundleId: 'com.example.marmita',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYksgN1iaL9FANPrIjjTbr-94VoVwgp4A',
    appId: '1:748368164925:ios:4ad375084d47ffd0665254',
    messagingSenderId: '748368164925',
    projectId: 'marmita-a24fd',
    storageBucket: 'marmita-a24fd.appspot.com',
    iosClientId: '748368164925-9ffe8lt89mn8lhe45u2tmpgqgqj7kj4c.apps.googleusercontent.com',
    iosBundleId: 'com.example.marmita.RunnerTests',
  );
}
